### ISSUE TITLE
Failing test without 'application_helper'

### ISSUE THREAD

**Issue by zakiva** [ManageIQ/manageiq-providers-kubernetes#131]
Test in `spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb` fails since the `application_helper` require statement was removed from the main repo in https://github.com/ManageIQ/manageiq/pull/16024. 

The error I'm getting is: 

```
Failures:

  1) ManageIQ::Providers::Kubernetes::MonitoringManager#authentication validates authentication with a proper response from message-buffer
     Failure/Error: expect(monitoring_manager.authentication_status_ok?).to be_truthy
     
       expected: truthy value
            got: false
     # ./spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb:46:in `block (4 levels) in <top (required)>'
     # /home/zakiva/.rvm/gems/ruby-2.3.3/gems/vcr-3.0.3/lib/vcr/util/variable_args_block_caller.rb:9:in `call_block'
     # /home/zakiva/.rvm/gems/ruby-2.3.3/gems/vcr-3.0.3/lib/vcr.rb:189:in `use_cassette'
     # ./spec/models/manageiq/providers/kubernetes/monitoring_manager_spec.rb:40:in `block (3 levels) in <top (required)>'

Finished in 47.65 seconds (files took 6.75 seconds to load)
1 example, 1 failure
```

I opened a [PR](https://github.com/ManageIQ/manageiq-providers-kubernetes/pull/125) to require `application_helper` in this repo, but I understand now that we prefer not to do that? 

@simon3z @moolitayer @cben  @jrafanie @Fryguy
