### ISSUE TITLE
Pod conditions fields != Node conditions fields

### ISSUE THREAD

**Issue by cben** [ManageIQ/manageiq-providers-kubernetes#183]
We use one table and one `parse_conditions()` method for both pod & node `status.conditions`.
The fields we take match node conditions but not exactly pods.  Specifically:

- nodes have `lastHeartbeatTime` which we parse & store;
- pods instead have `lastProbeTime` which we discard.

https://kubernetes.io/docs/api-reference/v1.8/#nodecondition-v1-core
https://kubernetes.io/docs/api-reference/v1.8/#podcondition-v1-core

Example from node:
```
    conditions:
    - lastHeartbeatTime: 2017-12-06T12:06:44Z
      lastTransitionTime: 2017-12-06T10:03:09Z
      message: kubelet has sufficient disk space available
      reason: KubeletHasSufficientDisk
      status: "False"
      type: OutOfDisk
```

example from pod:
```
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-12-06T10:19:15Z
      status: "True"
      type: Initialized
```
(but according to doc, may also have `message` and `reason`)
